# Generated by Django 5.2.3 on 2026-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sport_type', models.CharField(choices=[('jogging', 'Jogging'), ('beach_volley', 'Beach Volley'), ('bike', 'Biciclettata'), ('gym', 'Palestra'), ('tennis', 'Tennis'), ('soccer', 'Calcio'), ('basketball', 'Basket'), ('padel', 'Padel'), ('swimming', 'Nuoto'), ('yoga', 'Yoga'), ('hiking', 'Escursione')], max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('datetime', models.DateTimeField()),
                ('creator_id', models.CharField(max_length=50)),
                ('slack_channel', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
