# Generated by Django 5.2.3 on 2026-06-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='slack_channel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
