# Generated by Django 6.0.6 on 2026-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_sportevent_slack_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='sport_type',
            field=models.CharField(choices=[('jogging', 'Jogging'), ('beach_volley', 'Beach Volley'), ('bike', 'Biciclettata'), ('gym', 'Palestra'), ('tennis', 'Tennis'), ('soccer', 'Calcio'), ('basketball', 'Basket'), ('padel', 'Padel'), ('swimming', 'Nuoto'), ('yoga', 'Yoga'), ('hiking', 'Escursione'), ('chess', 'Scacchi'), ('videogames', 'Videogiochi')], max_length=20),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventparticipant'),
        ),
    ]
