# Generated by Django 5.2.3 on 2026-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventparticipant_alter_sportevent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='slack_ts',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='slack_channel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
