# Generated by Django 5.2.3 on 2026-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_sportevent_slack_ts_alter_sportevent_slack_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
